export const RESET_MESSAGE = "RESET_MESSAGE";
export const EXIT_PRODUCT_DETAIL_PAGE = "EXIT_PRODUCT_DETAIL_PAGE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const NEW_PRODUCTS_REQUEST = "NEW_PRODUCTS_REQUEST";
export const NEW_PRODUCTS_SUCCESS = "NEW_PRODUCTS_SUCCESS";
export const NEW_PRODUCTS_FAILURE = "NEW_PRODUCTS_FAILURE";

export const BEST_PRODUCTS_REQUEST = "BEST_PRODUCTS_REQUEST";
export const BEST_PRODUCTS_SUCCESS = "BEST_PRODUCTS_SUCCESS";
export const BEST_PRODUCTS_FAILURE = "BEST_PRODUCTS_FAILURE";

export const DETAIL_PRODUCT_REQUEST = "DETAIL_PRODUCT_REQUEST";
export const DETAIL_PRODUCT_SUCCESS = "DETAIL_PRODUCT_SUCCESS";
export const DETAIL_PRODUCT_FAILURE = "DETAIL_PRODUCT_FAILURE";

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILURE = "ADD_CART_FAILURE";

export const MY_CART_REQUEST = "MY_CART_REQUEST";
export const MY_CART_SUCCESS = "MY_CART_SUCCESS";
export const MY_CART_FAILURE = "MY_CART_FAILURE";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";

export const CHANGE_CART_REQUEST = "CHANGE_CART_REQUEST";
export const CHANGE_CART_SUCCESS = "CHANGE_CART_SUCCESS";
export const CHANGE_CART_FAILURE = "CHANGE_CART_FAILURE";
